Manager: DataUtils.h File Reference
DataUtils.h File Reference
Utility functions for filtering, extracting, and manipulating weather data collections.
#include "WeatherEntry.h"
#include "BST.h"
#include <map>
#include <string>
Functions
WeatherLog getRecordsByYearMonth (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap, int year, int month)
Get all records for a specific year/month combination.
WeatherLog getRecordsByMonth (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap, int month)
Get all records for a specific month across all years.
Vector< float > extractWindSpeeds (const WeatherLog &records)
Extracts wind speeds from a set of weather records.
Vector< float > extractTemperatures (const WeatherLog &records)
Extracts air temperatures from weather records.
Vector< float > extractSolarRadiation (const WeatherLog &records)
Extracts valid solar radiation values >= 100 from records.
float calculateTotalSolar (const Vector< float > &solarVals)
sums all solar radiation values in a vector and converts to kWh
Detailed Description
Utility functions for filtering, extracting, and manipulating weather data collections.
Author
Svetlana Alkhasova
Date
18/07/25
Version
1.0
Definition in file DataUtils.h.
Function Documentation
calculateTotalSolar()
float calculateTotalSolar (const Vector< float > & solarVals)
sums all solar radiation values in a vector and converts to kWh
Adds up all values, converts the sum to kilowatt-hours, and rounds the result to 1 decimal place.
Parameters
solarVals Vector of solar readings.
Returns
Total radiation in kWh (float, rounded).
Definition at line 51 of file DataUtils.cpp.
{
    float total = 0.0f;
    for(int i=0; i<solarVals.GetSize(); i++)
        total += solarVals[i] * (10.0f / 60.0f) / 1000.0f; //to convert Wh to kWh
    return std::round(total*10.0f)/10.0f;
}
References Vector< T >::GetSize().
Referenced by Menu::writeMonthStats().
extractSolarRadiation()
Vector< float > extractSolarRadiation (const WeatherLog & records)
Extracts valid solar radiation values >= 100 from records.
Includes only solar readings that are 100 or greater.
Parameters
records WeatherLog to process.
Returns
Vector<float> of valid solar radiation readings.
Definition at line 43 of file DataUtils.cpp.
{
    Vector<float> solar;
    for(int i=0; i<records.GetSize(); i++) {
        float sr = records[i].solarRadiation;
        if(!std::isnan(sr) && sr >= 100) solar.pushBack(sr);
    }
    return solar;
}
References Vector< T >::GetSize(), and Vector< T >::pushBack().
Referenced by Menu::writeMonthStats().
extractTemperatures()
Vector< float > extractTemperatures (const WeatherLog & records)
Extracts air temperatures from weather records.
Iterates through the WeatherLog and builds a vector of the temperature values found.
Parameters
records WeatherLog to extract from.
Returns
Vector<float> of temperatures.
Definition at line 38 of file DataUtils.cpp.
{
    Vector<float> temp;
    for(int i=0; i<records.GetSize(); i++) temp.pushBack(records[i].temperature);
    return temp;
}
References Vector< T >::GetSize(), and Vector< T >::pushBack().
Referenced by Menu::showTempStats(), and Menu::writeMonthStats().
extractWindSpeeds()
Vector< float > extractWindSpeeds (const WeatherLog & records)
Extracts wind speeds from a set of weather records.
Iterates over the WeatherLog and returns a vector containing only wind speed values.
Parameters
records WeatherLog of entries to process.
Returns
Vector<float> of wind speeds.
Definition at line 33 of file DataUtils.cpp.
{
    Vector<float> wind;
    for(int i=0; i<records.GetSize(); i++) wind.pushBack(records[i].windSpeed);
    return wind;
}
References Vector< T >::GetSize(), and Vector< T >::pushBack().
Referenced by Menu::showWindStats(), and Menu::writeMonthStats().
getRecordsByMonth()
WeatherLog getRecordsByMonth (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap, int month)
Get all records for a specific month across all years.
Combines weather records for the given month (all May's), searching over all available years in the tree/map.
Parameters
tree BST of available year-month keys (as year month strings).
dataMap Map from key (string) to WeatherLog.
month Month to filter (1-12).
Returns
WeatherLog containing all records for the given month, all years.
Definition at line 22 of file DataUtils.cpp.
{
    Vector<std::string> keys;
    tree.InOrder([](const std::string& s){});
    for(const auto& pair : dataMap) {
        std::string key = pair.first;
        int foundMonth = std::stoi(key.substr(5,2));
        if(foundMonth == month) return pair.second;
    }
    return WeatherLog();
}
References BST< T >::InOrder().
Referenced by Menu::showCorrelations().
getRecordsByYearMonth()
WeatherLog getRecordsByYearMonth (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap, int year, int month)
Get all records for a specific year/month combination.
Returns all weather records for a given year and month. The key is formatted as year month.
Parameters
tree Binary Search Tree holding all date keys as strings.
dataMap Map from key (string) to WeatherLog (vector of entries).
year Year to filter (2016).
month Month to filter (1-12).
Returns
WeatherLog containing the records for the specified year/month.
Definition at line 6 of file DataUtils.cpp.
{
    //to gather all BST keys
    Vector<std::string> keys;
    tree.InOrder([](const std::string& s){});
    //compose key as year/month
    std::stringstream keyBuilder;
    keyBuilder << year << "-";
    if(month < 10) keyBuilder << "0";
    keyBuilder << month;
    std::string key = keyBuilder.str();
    auto it = dataMap.find(key);
    if(it != dataMap.end()) return it->second;
    return WeatherLog();
}
References BST< T >::InOrder().
Referenced by Menu::showTempStats(), Menu::showWindStats(), Menu::writeAllStats(), and Menu::writeMonthStats().