Manager: BST< T > Class Template Reference
BST< T > Class Template Reference
Templated Binary Search Tree (BST) implementation.
#include <BST.h>
Public Member Functions
BST ()
Default constructor.
~BST ()
Destructor.
BST (const BST< T > &other)
Copy constructor for deep copy.
BST< T > & operator= (const BST< T > &otherTree)
Assignment operator (deep copy/cleanup)
void insert (const T &value)
Insert value into BST.
bool search (const T &value) const
Search for a value in the BST.
void InOrder (void(*process)(const T &)) const
In-order traversal (left, root, right).
void PreOrder (void(*process)(const T &)) const
Pre-order traversal (root, left, right).
void PostOrder (void(*process)(const T &)) const
Post-order traversal (left, right, root).
Private Member Functions
Node< T > * copy (Node< T > *node)
Helper to deep copy a subtree.
void destroy (Node< T > *node)
Helper for recursive destruction.
Node< T > * insert (Node< T > *node, const T &value)
Helper for recursive node insertion.
bool search (Node< T > *node, const T &value) const
Helper for recursive search in subtree.
void InOrder (Node< T > *node, void(*process)(const T &)) const
Helper for in-order traversal in subtree.
void PreOrder (Node< T > *node, void(*process)(const T &)) const
Helper for pre-order traversal in subtree.
void PostOrder (Node< T > *node, void(*process)(const T &)) const
Helper for post-order traversal in subtree.
Private Attributes
Node< T > * root
Root pointer.
Detailed Description
template<typename T>
class BST< T >
Templated Binary Search Tree (BST) implementation.
Provides methods for insertion, searching, copying, and three types of traversal using function pointers.
The tree stores values of type T which must implement comparison operators. All resources are properly managed for deep copy and destruction.
Author
Svetlana Alkhasova
Version
2.0
Date
18/07/25
Template Parameters
T Data type stored in BST nodes (must support comparison)
Definition at line 49 of file BST.h.
Constructor & Destructor Documentation
BST() [1/2]
template<typename T> BST< T >::BST ()
Default constructor.
Initializes an empty BST.
Definition at line 182 of file BST.h.
: root(NULL) {}
References root.
Referenced by BST(), and operator=().
~BST()
template<typename T> BST< T >::~BST ()
Destructor.
Frees all nodes and memory used by BST.
Definition at line 185 of file BST.h.
             {
    destroy(root);
    root = NULL;
}
References destroy(), and root.
BST() [2/2]
template<typename T> BST< T >::BST (const BST< T > & other)
Copy constructor for deep copy.
Parameters
other Another BST of the same type
Creates a new BST as a deep copy of another tree.
Definition at line 191 of file BST.h.
{
    root = copy(other.root);
}
References BST(), copy(), and root.
Member Function Documentation
copy()
template<typename T> Node< T > * BST< T >::copy (Node< T > * node) private
Helper to deep copy a subtree.
Parameters
node Subtree to copy.
Returns
Pointer to new subtree.
Definition at line 205 of file BST.h.
{
    if (!node) return NULL;
    Node<T>* newNode = new Node<T>;
    newNode->data = node->data;
    newNode->left = copy(node->left);
    newNode->right = copy(node->right);
    return newNode;
}
References copy(), Node< T >::data, Node< T >::left, and Node< T >::right.
Referenced by BST(), copy(), and operator=().
destroy()
template<typename T> void BST< T >::destroy (Node< T > * node) private
Helper for recursive destruction.
Parameters
node Subtree to destroy.
Definition at line 289 of file BST.h.
{
    if (!node) return;
    destroy(node->left);
    destroy(node->right);
    delete node;
    node = NULL;
}
References destroy(), Node< T >::left, and Node< T >::right.
Referenced by destroy(), operator=(), and ~BST().
InOrder() [1/2]
template<typename T> void BST< T >::InOrder (Node< T > * node, void(* process)(const T &)) const private
Helper for in-order traversal in subtree.
Parameters
node Subtree to process.
process Function pointer for processing node data.
Definition at line 255 of file BST.h.
{
    if (!node) return;
    InOrder(node->left, process);
    process(node->data);
    InOrder(node->right, process);
}
References Node< T >::data, InOrder(), Node< T >::left, and Node< T >::right.
InOrder() [2/2]
template<typename T> void BST< T >::InOrder (void(* process)(const T &)) const
In-order traversal (left, root, right).
Calls the given function pointer for each node in sorted order.
Parameters
process Function pointer to process each node's data.
Definition at line 250 of file BST.h.
{
    InOrder(root, process);
}
References InOrder(), and root.
Referenced by getRecordsByMonth(), getRecordsByYearMonth(), InOrder(), and InOrder().
insert() [1/2]
template<typename T> void BST< T >::insert (const T & value)
Insert value into BST.
Adds a new value to the tree. If the value already exists, it is not inserted again.
Parameters
value Value to be inserted.
Definition at line 215 of file BST.h.
{
    root = insert(root, value);
}
References insert(), and root.
Referenced by insert(), insert(), and FileHandler::processCSVLine().
insert() [2/2]
template<typename T> Node< T > * BST< T >::insert (Node< T > * node, const T & value) private
Helper for recursive node insertion.
Parameters
node Subtree to insert into.
value Value to insert.
Returns
Updated subtree pointer.
Definition at line 220 of file BST.h.
{
    if (!node) {
        Node<T>* newNode = new Node<T>;
        newNode->data = value;
        newNode->left = NULL;
        newNode->right = NULL;
        return newNode;
    }
    if (value < node->data)
        node->left = insert(node->left, value);
    else if (value > node->data)
        node->right = insert(node->right, value);
    return node;
}
References Node< T >::data, insert(), Node< T >::left, and Node< T >::right.
operator=()
template<typename T> BST< T > & BST< T >::operator= (const BST< T > & otherTree)
Assignment operator (deep copy/cleanup)
Parameters
otherTree BST to assign from.
Returns
Reference to this BST after assignment.
Definition at line 196 of file BST.h.
{
    if (this != &otherTree) {
        destroy(root);
        root = copy(otherTree.root);
    }
    return *this;
}
References BST(), copy(), destroy(), and root.
PostOrder() [1/2]
template<typename T> void BST< T >::PostOrder (Node< T > * node, void(* process)(const T &)) const private
Helper for post-order traversal in subtree.
Parameters
node Subtree to process.
process Function pointer for processing node data.
Definition at line 281 of file BST.h.
{
    if (!node) return;
    PostOrder(node->left, process);
    PostOrder(node->right, process);
    process(node->data);
}
References Node< T >::data, Node< T >::left, PostOrder(), and Node< T >::right.
PostOrder() [2/2]
template<typename T> void BST< T >::PostOrder (void(* process)(const T &)) const
Post-order traversal (left, right, root).
Calls the given function pointer for each node in post-order.
Parameters
process Function pointer to process each node's data.
Definition at line 276 of file BST.h.
{
    PostOrder(root, process);
}
References PostOrder(), and root.
Referenced by PostOrder(), and PostOrder().
PreOrder() [1/2]
template<typename T> void BST< T >::PreOrder (Node< T > * node, void(* process)(const T &)) const private
Helper for pre-order traversal in subtree.
Parameters
node Subtree to process.
process Function pointer for processing node data.
Definition at line 268 of file BST.h.
{
    if (!node) return;
    process(node->data);
    PreOrder(node->left, process);
    PreOrder(node->right, process);
}
References Node< T >::data, Node< T >::left, PreOrder(), and Node< T >::right.
PreOrder() [2/2]
template<typename T> void BST< T >::PreOrder (void(* process)(const T &)) const
Pre-order traversal (root, left, right).
Calls the given function pointer for each node in pre-order.
Parameters
process Function pointer to process each node's data.
Definition at line 263 of file BST.h.
{
    PreOrder(root, process);
}
References PreOrder(), and root.
Referenced by PreOrder(), and PreOrder().
search() [1/2]
template<typename T> bool BST< T >::search (const T & value) const
Search for a value in the BST.
Parameters
value Value to search for.
Returns
True if found, false otherwise.
Definition at line 236 of file BST.h.
{
    return search(root, value);
}
References root, and search().
Referenced by FileHandler::processCSVLine(), search(), and search().
search() [2/2]
template<typename T> bool BST< T >::search (Node< T > * node, const T & value) const private
Helper for recursive search in subtree.
Parameters
node Subtree to search.
value Value to search for.
Returns
True if value is found, else false.
Definition at line 241 of file BST.h.
{
    if (!node) return false;
    if (node->data == value) return true;
    if (value < node->data)
        return search(node->left, value);
    return search(node->right, value);
}
References Node< T >::data, Node< T >::left, Node< T >::right, and search().
Member Data Documentation
root
template<typename T> Node<T>* BST< T >::root private
Root pointer.
Definition at line 125 of file BST.h.
Referenced by BST(), BST(), InOrder(), insert(), operator=(), PostOrder(), PreOrder(), search(), and ~BST().
The documentation for this class was generated from the following file:
BST.h