Manager: Menu Class Reference
Menu Class Reference
Static utility class for main program menu and user interaction.
#include <Menu.h>
Static Public Member Functions
static void run (BST< std::string > &tree, std::map< std::string, WeatherLog > &dataMap)
Runs the main loop for the menu/user interface.
static void printMenu ()
Prints the main program menu for user selection.
static void showWindStats (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap)
Displays wind statistics (average and std dev) for user-selected month/year.
static void showTempStats (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap)
Displays temperature statistics for each month in a user-specified year.
static void showCorrelations (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap)
Calculates and displays Pearson correlations between parameters for given month.
static void writeMonthStats (std::ofstream &file, const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap, int year, int month)
Writes statistics for a single month to the supplied file.
static void writeAllStats (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap, const std::string &filename, int year)
Writes statistics for all months of a specified year to a file.
static void handleWriteToFile (const BST< std::string > &tree, const std::map< std::string, WeatherLog > &dataMap)
Handles user interaction and calls the writetofile operation.
static bool hasData (const WeatherLog &records, int month, int year, int option)
checks if records exist for a particular month/year or option.
static std::string monthName (int month)
Returns the name of a month given its number.
static void printCorrelation (const Vector< float > &v1, const Vector< float > &v2, const std::string &label)
Prints the correlation result between two parameter vectors.
Detailed Description
Static utility class for main program menu and user interaction.
Provides all functions related to presenting the menu, handling user choices, displaying calculated weather statistics, and writing summaries to output files. All functions are static and Menu is not meant to be instantiated.
Author
Svetlana Alkhasova
Version
2.1
Date
18/07/25
Definition at line 39 of file Menu.h.
Member Function Documentation
handleWriteToFile()
void Menu::handleWriteToFile (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap) static
Handles user interaction and calls the writetofile operation.
Parameters
tree BST of available keys.
dataMap WeatherLog map
prompts user for year and triggers output of statistics to CSV file.
Definition at line 172 of file Menu.cpp.
{
    int year = FileHandler::promptYear();
    writeAllStats(tree, dataMap, "WindTempSolar.csv", year);
    std::cout << "Data written to WindTempSolar.csv\n";
}
References FileHandler::promptYear(), and writeAllStats().
Referenced by run().
hasData()
bool Menu::hasData (const WeatherLog & records, int month, int year, int option) static
checks if records exist for a particular month/year or option.
Parameters
records WeatherLog as vector of entries.
month Month number (1-12).
year Year as integer.
option Used to change test logic for different menu actions.
Returns
True if records found for that selection, false otherwise.
Definition at line 32 of file Menu.cpp.
{
    if(records.GetSize() == 0) {
        if(opt == 1) std::cout << monthName(month) << " " << year << ": No Data\n";
        else std::cout << monthName(month) << ": No Data\n";
        return false;
    }
    return true;
}
References Vector< T >::GetSize(), and monthName().
Referenced by showCorrelations(), showTempStats(), and showWindStats().
monthName()
std::string Menu::monthName (int month) static
Returns the name of a month given its number.
Parameters
month Integer month (1 for January to 12 for December).
Returns
String name of the month.
Definition at line 41 of file Menu.cpp.
{
    const std::string names[] = {
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    };
    return (month >= 1 && month <= 12) ? names[month-1] : "Invalid";
}
Referenced by hasData(), showCorrelations(), showTempStats(), showWindStats(), and writeMonthStats().
printCorrelation()
void Menu::printCorrelation (const Vector< float > & v1, const Vector< float > & v2, const std::string & label) static
Prints the correlation result between two parameter vectors.
Parameters
v1 First data vector.
v2 Second data vector.
label Label for correlation type (S_T, S_R, R_T).
Definition at line 78 of file Menu.cpp.
{
    try {
        double value = pearson(v1, v2);
        std::cout << lbl << ": ";
        if(std::isnan(value))
            std::cout << "NaN";
        else
            std::cout << std::fixed << std::setprecision(2) << value;
        std::cout << std::endl;
    } catch(const std::exception& e) {
        std::cout << "Error (" << lbl << "): " << e.what() << std::endl;
    }
}
References pearson().
Referenced by showCorrelations().
printMenu()
void Menu::printMenu () static
Prints the main program menu for user selection.
Definition at line 23 of file Menu.cpp.
                     {
    std::cout << "Menu options are:\n";
    std::cout << "1. Calculate average wind speed and std dev for month and year\n";
    std::cout << "2. Calculate average temperature and std dev for each month in year\n";
    std::cout << "3. Calculate sPCC for (S_T, S_R, T_R) for a selected month for all years.\n";
    std::cout << "4. Write all stats to file\n";
    std::cout << "5. Exit the program.\n";
}
Referenced by run().
run()
void Menu::run (BST< std::string > & tree, std::map< std::string, WeatherLog > & dataMap) static
Runs the main loop for the menu/user interface.
Parameters
tree BST holding all year-month keys (as strings).
dataMap Map from string key to WeatherLog, holding all records.
Presents the menu, receives user choices, and calls the appropriate functions to display stats or export data, looping until the user exits.
Definition at line 5 of file Menu.cpp.
{
    int option = 0;
    do {
        std::cout << "\n";
        printMenu();
        std::cout << "Enter your choice (1-5): ";
        std::cin >> option;
        switch (option) {
            case 1: showWindStats(tree, dataMap); break;
            case 2: showTempStats(tree, dataMap); break;
            case 3: showCorrelations(tree, dataMap); break;
            case 4: handleWriteToFile(tree, dataMap); break;
            case 5: std::cout << "Exiting the program.\n"; break;
            default: std::cout << "Invalid choice.\n";
        }
    } while(option != 5);
}
References handleWriteToFile(), printMenu(), showCorrelations(), showTempStats(), and showWindStats().
Referenced by main().
showCorrelations()
void Menu::showCorrelations (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap) static
Calculates and displays Pearson correlations between parameters for given month.
Parameters
tree BST of available keys.
dataMap WeatherLog data map.
Definition at line 92 of file Menu.cpp.
{
    int month = FileHandler::promptMonth();
    WeatherLog data = getRecordsByMonth(tree, dataMap, month);
    if(!hasData(data, month, -1, 1)) return;
    //pairwise deletion for S_T, S_R, T_R
    Vector<float> s_t1, s_t2, s_r1, s_r2, t_r1, t_r2;
    for(int i=0;i<data.GetSize();i++) {
        float s = data[i].windSpeed, t = data[i].temperature, r = data[i].solarRadiation;
        if(!std::isnan(s) && !std::isnan(t))           { s_t1.pushBack(s); s_t2.pushBack(t); }
        if(!std::isnan(s) && !std::isnan(r) && r>=100) { s_r1.pushBack(s); s_r2.pushBack(r); }
        if(!std::isnan(t) && !std::isnan(r) && r>=100) { t_r1.pushBack(t); t_r2.pushBack(r); }
    }
    std::cout << "Sample Pearson Correlation Coefficients sPCC for " << monthName(month) << ":\n";
    printCorrelation(s_t1, s_t2, "S_T");
    printCorrelation(s_r1, s_r2, "S_R");
    printCorrelation(t_r1, t_r2, "T_R");
}
References getRecordsByMonth(), Vector< T >::GetSize(), hasData(), monthName(), printCorrelation(), FileHandler::promptMonth(), and Vector< T >::pushBack().
Referenced by run().
showTempStats()
void Menu::showTempStats (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap) static
Displays temperature statistics for each month in a user-specified year.
Parameters
tree BST of valid year-month keys.
dataMap Map of weather logs keyed by year/month.
Definition at line 63 of file Menu.cpp.
{
    int year = FileHandler::promptYear();
    std::cout << year << "\n";
    for(int month=1; month<=12; ++month) {
        WeatherLog data = getRecordsByYearMonth(tree, dataMap, year, month);
        if(!hasData(data, month, year, 2)) continue;
        Vector<float> temps = extractTemperatures(data);
        float avgv = mean(temps);
        float sdv = stdev(temps);
        std::cout << monthName(month) << ": average: "
                  << std::fixed << std::setprecision(1) << avgv
                  << " degree C, std dev: " << sdv << "\n";
    }
}
References extractTemperatures(), getRecordsByYearMonth(), hasData(), mean(), monthName(), FileHandler::promptYear(), and stdev().
Referenced by run().
showWindStats()
void Menu::showWindStats (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap) static
Displays wind statistics (average and std dev) for user-selected month/year.
Parameters
tree BST of valid year-month keys.
dataMap Source map for weather logs.
Definition at line 49 of file Menu.cpp.
{
    int year = FileHandler::promptYear();
    int month = FileHandler::promptMonth();
    WeatherLog data = getRecordsByYearMonth(tree, dataMap, year, month);
    if(!hasData(data, month, year, 1)) return;
    Vector<float> speeds = extractWindSpeeds(data);
    float avg = mean(speeds)*3.6f;
    float sd = stdev(speeds)*3.6f;
    std::cout << monthName(month) << " " << year << ": "
              << "Average wind speed: " << std::fixed << std::setprecision(1) << avg
              << " km/h, Std dev: " << sd << " km/h\n";
}
References extractWindSpeeds(), getRecordsByYearMonth(), hasData(), mean(), monthName(), FileHandler::promptMonth(), FileHandler::promptYear(), and stdev().
Referenced by run().
writeAllStats()
void Menu::writeAllStats (const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap, const std::string & filename, int year) static
Writes statistics for all months of a specified year to a file.
Parameters
tree BST of keys.
dataMap WeatherLog records.
filename Output file name.
year The selected year.
Definition at line 155 of file Menu.cpp.
{
    std::ofstream file(filename);
    if(!file) {
        std::cerr << "Error opening output file: " << filename << std::endl;
        return;
    }
    file << year << "\n";
    bool any = false;
    for(int month=1; month<=12; ++month) {
        if(getRecordsByYearMonth(tree, dataMap, year, month).GetSize()>0) {
            writeMonthStats(file, tree, dataMap, year, month);
            any = true;
        }
    }
    if(!any) file << "No Data";
}
References getRecordsByYearMonth(), and writeMonthStats().
Referenced by handleWriteToFile().
writeMonthStats()
void Menu::writeMonthStats (std::ofstream & file, const BST< std::string > & tree, const std::map< std::string, WeatherLog > & dataMap, int year, int month) static
Writes statistics for a single month to the supplied file.
Parameters
file Output file stream (already open and ready).
tree BST of year/month keys.
dataMap Map of records.
year Year as integer.
month Month number (1-12).
Definition at line 112 of file Menu.cpp.
{
    WeatherLog data = getRecordsByYearMonth(tree, dataMap, year, month);
    if(data.GetSize() == 0) return;
    Vector<float> wind = extractWindSpeeds(data), temp = extractTemperatures(data), solar = extractSolarRadiation(data);
    float wAvg = mean(wind)*3.6f, wStdev = stdev(wind)*3.6f, wMad = 0;
    float tAvg = mean(temp), tStdev = stdev(temp), tMad = 0;
    float solarTotal = calculateTotalSolar(solar);
    //compute MAD (Mean Absolute Deviation, 1 decimal) for wind
    float wMean = mean(wind)*3.6f;
    int w_n = 0;
    for(int i=0; i<wind.GetSize(); i++) {
        if(!std::isnan(wind[i])) { wMad += std::abs(wind[i]*3.6f - wMean); w_n++; }
    }
    if(w_n>0) wMad /= w_n;
    //compute MAD for temp
    float tMean = mean(temp);
    int t_n = 0;
    for(int i=0; i<temp.GetSize(); i++) {
        if(!std::isnan(temp[i])) { tMad += std::abs(temp[i] - tMean); t_n++; }
    }
    if(t_n>0) tMad /= t_n;
    file << monthName(month) << ",";
    if(!std::isnan(wAvg))
        file << std::fixed << std::setprecision(1)
             << wAvg << "(" << wStdev << ", " << wMad << "),";
    else
        file << " ,";
    if(!std::isnan(tAvg))
        file << std::fixed << std::setprecision(1)
             << tAvg << "(" << tStdev << ", " << tMad << "),";
    else
        file << " ,";
    if(!std::isnan(solarTotal))
        file << std::fixed << std::setprecision(1) << solarTotal;
    else
        file << " ";
    file << "\n";
}
References calculateTotalSolar(), extractSolarRadiation(), extractTemperatures(), extractWindSpeeds(), getRecordsByYearMonth(), Vector< T >::GetSize(), mean(), monthName(), and stdev().
Referenced by writeAllStats().
The documentation for this class was generated from the following files:
Menu.h
Menu.cpp