Manager: FileHandler Class Reference
FileHandler Class Reference
Static utility class for file and stream operations, user input, and parsing.
#include <FileHandler.h>
Static Public Member Functions
static std::istream & readDate (std::istream &is, Date &date)
Reads a Date from an input stream in day/month/year format.
static std::ostream & printDate (std::ostream &os, const Date &d)
Prints a Date to an output stream as day/month/year.
static std::istream & readTime (std::istream &is, MyTime &t)
Reads a MyTime (HH:MM) from an input stream.
static std::ostream & printTime (std::ostream &os, const MyTime &t)
Prints a MyTime to an output stream as HH:MM.
static int promptYear ()
Prompts the user for a year, with validation.
static int promptMonth ()
Prompts the user for a month (1-12), with validation.
static bool loadDataFiles (BST< std::string > &dateTree, std::map< std::string, WeatherLog > &dataMap)
Loads weather data files into the BST and dataMap.
static bool parseCSV (const std::string &filename, BST< std::string > &dateTree, std::map< std::string, WeatherLog > &dataMap)
Parses a single CSV file into the BST and dataMap.
static std::map< std::string, int > buildColumnMap (const std::string &headerLine)
Builds a column name-to-index map from a CSV header line.
static void processCSVLine (const std::string &line, const std::map< std::string, int > &colMap, BST< std::string > &dateTree, std::map< std::string, WeatherLog > &dataMap)
Processes a line from a CSV file and adds entry to data structures.
static Date parseDate (const std::string &dateTimeStr)
Parses a Date from a combined date-time string.
static MyTime parseTime (const std::string &dateTimeStr)
Parses a MyTime from a combined date-time string.
Detailed Description
Static utility class for file and stream operations, user input, and parsing.
All functions are static and designed to help with reading/writing weather data, inputting dates/times, and parsing CSV fields into the project’s main structures.
This class is not intended to be instantiated.
Author
Svetlana Alkhasova
Version
2.0
Date
19/07/25
Definition at line 40 of file FileHandler.h.
Member Function Documentation
buildColumnMap()
std::map< std::string, int > FileHandler::buildColumnMap (const std::string & headerLine) static
Builds a column name-to-index map from a CSV header line.
Parameters
headerLine The header string, comma separated.
Returns
Map from column name to column index.
Definition at line 129 of file FileHandler.cpp.
{
    std::map<std::string, int> colMap;
    std::stringstream ss(headerLine);
    std::string col;
    int idx = 0;
    while (std::getline(ss, col, ',')) {
        colMap[col] = idx++;
    }
    return colMap;
}
Referenced by parseCSV().
loadDataFiles()
bool FileHandler::loadDataFiles (BST< std::string > & dateTree, std::map< std::string, WeatherLog > & dataMap) static
Loads weather data files into the BST and dataMap.
Reads all relevant CSV files as specified by the assignment, parsing each and populating the BST and map structures.
Parameters
dateTree BST to store date keys.
dataMap Map from date key to WeatherLog.
Returns
True on success, false on file read error.
Precondition
Data files must exist in the expected location.
Definition at line 93 of file FileHandler.cpp.
{
    std::ifstream srcList("data/data_source.txt");
    if (!srcList.is_open()) {
        std::cerr << "Could not open data_source.txt" << std::endl;
        return false;
    }
    std::string filename;
    bool loaded = false;
    while (std::getline(srcList, filename)) {
        if (filename.empty()) continue;
        if (parseCSV("data/" + filename, dateTree, dataMap)) loaded = true;
    }
    return loaded;
}
References parseCSV().
Referenced by main().
parseCSV()
bool FileHandler::parseCSV (const std::string & filename, BST< std::string > & dateTree, std::map< std::string, WeatherLog > & dataMap) static
Parses a single CSV file into the BST and dataMap.
Parameters
filename Path to the CSV file.
dateTree BST to store extracted date keys.
dataMap Map from date key to WeatherLog.
Returns
True if file successfully read, false otherwise.
Definition at line 109 of file FileHandler.cpp.
{
    std::ifstream file(filename);
    if(!file.is_open()) {
        std::cerr << "Could not open: " << filename << std::endl;
        return false;
    }
    std::string header;
    if (!std::getline(file, header)) {
        std::cerr << "Empty CSV or unreadable: " << filename << std::endl;
        return false;
    }
    std::map<std::string, int> colMap = buildColumnMap(header);
    std::string line;
    while (std::getline(file, line)) {
        processCSVLine(line, colMap, dateTree, dataMap);
    }
    return true;
}
References buildColumnMap(), and processCSVLine().
Referenced by loadDataFiles().
parseDate()
Date FileHandler::parseDate (const std::string & dateTimeStr) static
Parses a Date from a combined date-time string.
Parameters
dateTimeStr String in combined day/moth/year hh:mm or similar format.
Returns
Date object with parsed day, month, year values.
Definition at line 181 of file FileHandler.cpp.
{
    int day, month, year;
    char slash;
    std::stringstream ss(dateStr);
    ss >> day >> slash >> month >> slash >> year;
    if (slash != '/') throw std::runtime_error("Invalid date format (expected /)");
    Date d;
    d.SetDay(day);
    d.SetMonth(month);
    d.SetYear(year);
    return d;
}
References Date::SetDay(), Date::SetMonth(), and Date::SetYear().
Referenced by processCSVLine().
parseTime()
MyTime FileHandler::parseTime (const std::string & dateTimeStr) static
Parses a MyTime from a combined date-time string.
Parameters
dateTimeStr String in combined day/moth/year hh:mm or similar format.
Returns
MyTime object with parsed hour and minute values.
Definition at line 195 of file FileHandler.cpp.
{
    int hour, minute;
    char colon;
    std::stringstream ss(timeStr);
    ss >> hour >> colon >> minute;
    if (colon != ':') throw std::runtime_error("Invalid time format (expected :)");
    MyTime t;
    t.SetHour(hour);
    t.SetMinute(minute);
    return t;
}
References MyTime::SetHour(), and MyTime::SetMinute().
Referenced by processCSVLine().
printDate()
std::ostream & FileHandler::printDate (std::ostream & os, const Date & d) static
Prints a Date to an output stream as day/month/year.
Parameters
os Output stream.
d Date object to print.
Returns
Reference to the output stream (os).
Definition at line 28 of file FileHandler.cpp.
{
    os << (d.GetDay() < 10 ? "0" : "") << d.GetDay() << "/"
       << (d.GetMonth() < 10 ? "0" : "") << d.GetMonth() << "/"
       << d.GetYear();
    return os;
}
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
printTime()
std::ostream & FileHandler::printTime (std::ostream & os, const MyTime & t) static
Prints a MyTime to an output stream as HH:MM.
Parameters
os Output stream.
t MyTime object to print.
Returns
Reference to the output stream (os).
Definition at line 54 of file FileHandler.cpp.
{
    os << (t.GetHour() < 10 ? "0" : "") << t.GetHour() << ":"
       << (t.GetMinute() < 10 ? "0" : "") << t.GetMinute();
    return os;
}
References MyTime::GetHour(), and MyTime::GetMinute().
processCSVLine()
void FileHandler::processCSVLine (const std::string & line, const std::map< std::string, int > & colMap, BST< std::string > & dateTree, std::map< std::string, WeatherLog > & dataMap) static
Processes a line from a CSV file and adds entry to data structures.
This helper parses the line, extracts fields, constructs a WeatherEntry, and updates the BST and dataMap as required.
Parameters
line A single non-header line from the CSV.
colMap Map from column names to indices (from buildColumnMap).
dateTree BST to update (if new date key is found).
dataMap Map from key to WeatherLog to update.
Definition at line 141 of file FileHandler.cpp.
{
    std::stringstream ss(line);
    std::string cell;
    Vector<std::string> fields;
    while (std::getline(ss, cell, ',')) {
        fields.pushBack(cell);
    }
    //extract and parse fields.
    //Expects day/month/year for date, hh:mm for time.
    try {
        std::string dateTimeStr = fields[colMap.at("WAST")];
        // If CSV entry is "15/07/2025 09:45"
        std::stringstream dts(dateTimeStr);
        std::string datePart, timePart;
        std::getline(dts, datePart, ' ');
        std::getline(dts, timePart);
        Date date = parseDate(datePart);
        MyTime time = parseTime(timePart);
        float wind = fields[colMap.at("S")].empty() ? NAN : std::stof(fields[colMap.at("S")]);
        float temp = fields[colMap.at("T")].empty() ? NAN : std::stof(fields[colMap.at("T")]);
        float solar = fields[colMap.at("SR")].empty() ? NAN : std::stof(fields[colMap.at("SR")]);
        WeatherEntry w {date, time, wind, temp, solar};
        //key is year month as string
        std::string key = std::to_string(date.GetYear()) + "-" + (date.GetMonth() < 10 ? "0" : "") + std::to_string(date.GetMonth());
        dataMap[key].pushBack(w);
        if (!dateTree.search(key)) {
            dateTree.insert(key);
        }
    } catch (...) {
        //skip any problematic lines
    }
}
References Date::GetMonth(), Date::GetYear(), BST< T >::insert(), parseDate(), parseTime(), Vector< T >::pushBack(), and BST< T >::search().
Referenced by parseCSV().
promptMonth()
int FileHandler::promptMonth () static
Prompts the user for a month (1-12), with validation.
Returns
Valid month number (integer).
Definition at line 77 of file FileHandler.cpp.
{
    int month;
    while (true) {
        std::cout << "Enter month (1-12): ";
        std::cin >> month;
        if (std::cin.fail() || month < 1 || month > 12) {
            std::cin.clear();
            std::cin.ignore(10000, '\n');
            std::cout << "Invalid month, please try again." << std::endl;
        } else {
            return month;
        }
    }
}
Referenced by Menu::showCorrelations(), and Menu::showWindStats().
promptYear()
int FileHandler::promptYear () static
Prompts the user for a year, with validation.
Returns
Valid year (integer).
Definition at line 61 of file FileHandler.cpp.
{
    int year;
    while (true) {
        std::cout << "Enter year: ";
        std::cin >> year;
        if (std::cin.fail() || year < 1800 || year > 2100) {
            std::cin.clear();
            std::cin.ignore(10000, '\n');
            std::cout << "Invalid year, please try again." << std::endl;
        } else {
            return year;
        }
    }
}
Referenced by Menu::handleWriteToFile(), Menu::showTempStats(), and Menu::showWindStats().
readDate()
std::istream & FileHandler::readDate (std::istream & is, Date & date) static
Reads a Date from an input stream in day/month/year format.
Parameters
is Input stream to read from.
date Date object to store result in.
Returns
Reference to the input stream is.
Definition at line 9 of file FileHandler.cpp.
{
    int day, month, year;
    char slash;
    is >> day >> slash >> month >> slash >> year;
    if (slash != '/') {
        is.setstate(std::ios::failbit);
        return is;
    }
    try {
        date.SetDay(day);
        date.SetMonth(month);
        date.SetYear(year);
    } catch (...) {
        is.setstate(std::ios::failbit);
    }
    return is;
}
References Date::SetDay(), Date::SetMonth(), and Date::SetYear().
readTime()
std::istream & FileHandler::readTime (std::istream & is, MyTime & t) static
Reads a MyTime (HH:MM) from an input stream.
Parameters
is Input stream.
t MyTime object to store result.
Returns
Reference to the input stream (is).
Definition at line 36 of file FileHandler.cpp.
{
    int hour, minute;
    char colon;
    is >> hour >> colon >> minute;
    if (colon != ':') {
        is.setstate(std::ios::failbit);
        return is;
    }
    try {
        t.SetHour(hour);
        t.SetMinute(minute);
    } catch (...) {
        is.setstate(std::ios::failbit);
    }
    return is;
}
References MyTime::SetHour(), and MyTime::SetMinute().
The documentation for this class was generated from the following files:
FileHandler.h
FileHandler.cpp