Manager: Date Class Reference
Date Class Reference
Represents a calendar date (day/month/year).
#include <Date.h>
Public Member Functions
Date ()
Default constructor. Initializes to an empty or zero date.
int GetDay () const
Gets the day component.
int GetMonth () const
Gets the month component.
int GetYear () const
Gets the year component.
void SetDay (int day)
Sets the day component. Range-checked.
void SetMonth (int month)
Sets the month component. Range-checked.
void SetYear (int year)
Sets the year component.
Private Attributes
int day
Day of the month.
int month
Month number (1-12)
int year
Year.
Detailed Description
Represents a calendar date (day/month/year).
Provides accessors (getters) and mutators (setters) for each date component, with simple validation to ensure day, month, and year are in a valid range.
Definition at line 23 of file Date.h.
Constructor & Destructor Documentation
Date()
Date::Date ()
Default constructor. Initializes to an empty or zero date.
Definition at line 6 of file Date.cpp.
: day(-1), month(-1), year(-2000) {}
References day, month, and year.
Member Function Documentation
GetDay()
int Date::GetDay () const
Gets the day component.
Returns
Day of month (1-31).
Definition at line 8 of file Date.cpp.
                       {
    return day;
}
References day.
Referenced by FileHandler::printDate().
GetMonth()
int Date::GetMonth () const
Gets the month component.
Returns
Month number (1-12).
Definition at line 11 of file Date.cpp.
{
    return month;
}
References month.
Referenced by FileHandler::printDate(), and FileHandler::processCSVLine().
GetYear()
int Date::GetYear () const
Gets the year component.
Returns
Year
Definition at line 14 of file Date.cpp.
{
    return year;
}
References year.
Referenced by FileHandler::printDate(), and FileHandler::processCSVLine().
SetDay()
void Date::SetDay (int day)
Sets the day component. Range-checked.
Parameters
day Day of the month (should be 1-31).
Definition at line 18 of file Date.cpp.
                       {
    if (d < 1 || d > 31) throw std::invalid_argument("Day must be 1-31");
    day = d;
}
References day.
Referenced by FileHandler::parseDate(), and FileHandler::readDate().
SetMonth()
void Date::SetMonth (int month)
Sets the month component. Range-checked.
Parameters
month Month number (should be 1-12).
Definition at line 23 of file Date.cpp.
{
    if (m < 1 || m > 12) throw std::invalid_argument("Month must be 1-12");
    month = m;
}
References month.
Referenced by FileHandler::parseDate(), and FileHandler::readDate().
SetYear()
void Date::SetYear (int year)
Sets the year component.
Parameters
year Full year
Definition at line 28 of file Date.cpp.
{
    year = y;
}
References year.
Referenced by FileHandler::parseDate(), and FileHandler::readDate().
Member Data Documentation
day
int Date::day private
Day of the month.
Definition at line 69 of file Date.h.
Referenced by Date(), GetDay(), and SetDay().
month
int Date::month private
Month number (1-12)
Definition at line 70 of file Date.h.
Referenced by Date(), GetMonth(), and SetMonth().
year
int Date::year private
Year.
Definition at line 71 of file Date.h.
Referenced by Date(), GetYear(), and SetYear().
The documentation for this class was generated from the following files:
Date.h
Date.cpp